logging:
  level:
    org:
      hibernate: INFO
      springframework:
        root: INFO
        web: INFO

application:
  data:
    fill:
      category: false

springdoc:
  swagger-ui:
    path: /

spring:
  datasource:
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate

  sql:
    init:
      mode: always
      data-locations: classpath*:sql/data/category.sql
      schema-locations: