logging:
  level:
    org:
      hibernate: INFO
      springframework:
        root: INFO
        web: INFO

spring:
  datasource:
    username: dev
    password:
    url: jdbc:h2:mem:dev

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
      data-locations: classpath*:sql/data/category.sql
      schema-locations: